gestionContactos/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ContactosController@index');
Route::get('index', 'ContactosController@index');
Route::get('/delete/{id}','ContactosController@delete_view');
Route::post('/contacto','ContactosController@store');
Route::resource('contactos', 'ContactosController');
Route::delete('/destroy/{id}','ContactosController@destroy');

Route::get('/cargaJSON', function () {
    return view('cargaJSON');
});

Route::get('/exportar','ExportController@export');

gestionContactos/app/Contacto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

//Modelo para la tabla table_contacto
class Contacto extends Model
{

	 protected $table = "table_contacto";//nombre de la tabla de la bdd
    

    protected $fillable = [ //campos a tratar en el sistema.
        'Nombre', 'Apellido', 'Email'
    ];



}

gestionContactos/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

gestionContactos/app/Http/Controllers/ContactosController.php
<?php

namespace App\Http\Controllers;

use App\Contacto;
use Illuminate\Http\Request;
use App\Exports\ContactExport;
use Maatwebsite\Excel\Facades\Excel;
use DB;


class ContactosController extends Controller
{

    public function index()//redirecciona a indice
    {
        $contacto= Contacto::all();
        return view('index')->with('contacto', $contacto);
    }

     public function getContacto()
    {
        return Contacto::all();
    }

    public function delete_view($id)//redirecciona a delete con el identificador de contacto
    {
      return view('delete')->with('id', $id);
    }


    public function create()//redirecciona a la pagina de crear un nuevo contacto
    {
        return view('create');
    }

      public function store(Request $request)//crea un nuevo contacto
    {
        $contacto = new Contacto;
        $contacto->Nombre=$request->input('Nombre');
        $contacto->Apellido=$request->input('Apellido');
        $contacto->Email=$request->input('Email');
        $contacto-> save();
          return redirect()->route('contactos.index');
    }

    public function edit($id){//redirecciona a la pagina edit y devuelve el contacto a editar.
    	$contacto= Contacto::find($id);
    	return view ('edit')->with('contacto', $contacto);
    }


    public function update(Request $request, $id)//Actualiza un contacto
    {
        $contacto= Contacto::find($id);
        $contacto->Nombre=$request->input('nombre');
        $contacto->Apellido=$request->input('apellido');
        $contacto->Email=$request->input('email');
        $contacto->save();

        return redirect()->route('contactos.index');
    }

    public function destroy($id)//Elimina un contacto
    {
         Contacto::destroy($id);
        return redirect()->route('contactos.index');
    }

       public function show($id)
    {
        $contacto=Contacto::find($id);
        return  view('index',compact('contacto'));
    }
}

gestionContactos/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

gestionContactos/app/Http/Controllers/ExportController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Exports\ContactExport;
use Maatwebsite\Excel\Facades\Excel;
use DB;


class ExportController extends Controller{

     public function export()
    {
    
        return Excel::download(new ContactExport, 'contacts.xlsx');
    }

}

gestionContactos/resources/views/cargaJSON.blade.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$conexion = mysqli_connect("localhost:3306", "root", "", "gestioncontactos") or die("Problemas con la conexión");

$registros = mysqli_query($conexion, "select * from table_contacto") or die("Problemas en el select" . mysqli_error($conexion));

while ($reg = mysqli_fetch_array($registros)) {
    $vec[] = $reg;
}

$cad = json_encode ($vec);
echo $cad;

gestionContactos/resources/views/create.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
       
        </style>
    </head>
    <body>
  
         <form method="post" action="/contacto">
             <input type="hidden" name="_method" value="post">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
             Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="Nombre" id="Nombre"><br>
            Last name<input type="text" name="Apellido" id="Apellido"><br>
            Email&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="Email" id="Email"><br>
            <input type="submit" value="Add">
        </form>
  


    </body>
</html>

gestionContactos/resources/views/delete.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
        
        </style>
    </head>
    <body>


        <h3>Éstas seguro de borrar el registro?</h3>
         <form method="post" action="{{ route('contactos.destroy',$id) }})">
             @method('DELETE')
             @csrf
       
      
            <input type="submit" value="Accept">
        </form>



    </body>
</html>

gestionContactos/resources/views/edit.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
        
        </style>
    </head>
    <body>



    Id:{{ $contacto->id }}
    Nombre: {{ $contacto->Nombre }}
     Email: {{ $contacto->Email }}
        <form method="post" action="{{ route('contactos.update',$contacto->id) }})">
             @method('PUT')
             @csrf
            Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="nombre" id="nombre"><br>
            Last name<input type="text" name="apellido" id="apellido"><br>
            Email&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="email" id="email"><br>
            <input type="submit" id='boton' value="Edit">
        </form>

        

    </body>
</html>

gestionContactos/resources/views/index.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <script type="text/javascript" src="{{ URL::asset('/includes/prototype.js') }}"></script>
        <script type="text/javascript" src="{{ URL::asset('/includes/scriptaculous.js?load=effects') }}"></script>
        <script type="text/javascript" src="{{ URL::asset('/includes/modalbox.js') }}"></script>
        <link rel="stylesheet" href="{{ URL::asset('css/modalbox.css') }}" type="text/css" media="screen" />
         <script type="text/javascript" src="{{ URL::asset('/js/funciones.js') }}"></script>

        <!-- Styles -->
        <style>
        table,td{
            border: 1px solid black;
            text-align: center;
        }
        table{
            margin-left: 36%;
            margin-right: 35%;
        }
        h2{
            color: #B1B0B0;
            text-align: center;
        }
        #add-export-button{
           margin-left: 48%;
            margin-right: 40% ;
        }
        td{
            background-color: #B1B0B0;
        }
        </style>
    </head>
    <body>

<h2>CONTACTOS</h2>



 <div id="resultados"></div>
        <script>
            myFunction();
     function myFunction() {
 setInterval(presionBoton, 500);}
</script>


<br>
<div id="add-export-button">
<a href="/contactos/create" title="Add" onClick="Modalbox.show(this.href, {title: this.title, width: 600}); return false;"><button id="create" type="button">Add</button></a>
</br></br>
<a href="/exportar"><button id="create" type="button">Export in Excell</button></a>
</div>

<div id="tabla">
    
</div>


    </body>
</html>